repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==21.11.29]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==21.12b0]
    args: ["--target-version", "py35"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    language_version: python3
    files: ^src/webargs/
    additional_dependencies: ["marshmallow>=3,<4"]
