# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
    - pip install -U pytest mock flask django webtest bottle tornado
    - pip install -U .

script: py.test
