name: build
on:
  push:
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install tox
      - run: python -m tox -e mypy

  test:
    strategy:
      matrix:
        tox-factor: [""]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - python-version: "3.10"
            tox-factor: "-marshmallowdev"
          - python-version: "3.7"
            tox-factor: "-mindeps"
    name: "test py${{ matrix.python-version }}${{ matrix.tox-factor }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install tox
      - run: python -m tox -e py${{ matrix.tox-factor }}

  twine-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install requirements
        run: python -m pip install build twine
      - name: build dists
        run: python -m build
      - name: check package metadata
        run: twine check dist/*
